### ISSUE TITLE
massUpdateHost failing validation when successful

### ISSUE THREAD

**Issue by angelosanramon** [sumitgoelpw/zabbix-promise#1]
MassUpdateHost is returning a hash for the returned body.result when it is successful. This is causing a promise reject.

Example of the returned body:

{
  "jsonrpc": "2.0",
  "result": {
    "hostids": [
      "10105",
      "10106",
      "10107",
      "10108",
      "10109",
      "10110"
    ]
  },
  "id": 4
}

**Comment by sumitgoelpw** [comment]
@angelosanramon Seems like the extra validation was unnecessary. Please update to latest version and your issue should be solved now. I have added additional test cases for the same.

**Comment by angelosanramon** [comment]
@sumitgoelpw Cool. Thanks Sumit. Appreciate the fix.
