### ISSUE TITLE
Add support for custom options

### ISSUE THREAD

**Issue by MadsRC** [sumitgoelpw/zabbix-promise#10]
From reading the code, I can't really see if it's possible to parse options such as use a specific CA when validating a HTTPS request (I need to use this library to connect to a host signed by an internal ca)

From reading this: https://github.com/request/request#tlsssl-protocol it seems like it should be possible to add custom options using `https.globalAgent.options` however that doesn't seem to work.

Any idea?

**Comment by MadsRC** [comment]
I should add that I'm aware of the `rejectUnauthorized:false` option. However that is a no go for production usage.

**Comment by sumitgoelpw** [comment]
@MadsRC thank you for the suggestion. I will look into the possibilities for the next release hopefully sometime this week. It should be doable. In the mean time, you may want to try [ssl-root-cas](https://www.npmjs.com/package/ssl-root-cas).

**Comment by sumitgoelpw** [comment]
@MadsRC I've added the ability to pass the [request options](https://github.com/request/request#requestoptions-callback) as an object via the fourth parameter in the Zabbix class instantiation.

```
const Zabbix = require('zabbix-promise');

const zabbix = new Zabbix(
  'http://127.0.0.1:8080/api_jsonrpc.php',
  'Admin',
  'zabbix', {
    'agentOptions': {
      'securityOptions': 'SSL_OP_NO_SSLv3'
    }
  }
);
```

It is in the devel branch now; please give it a try and let me know if you encounter any issues. Soon it will be merged into the master branch.

**Comment by sumitgoelpw** [comment]
Pull request #11
