### ISSUE TITLE
#Doubts

### ISSUE THREAD

**Issue by ImSuriya** [sumitgoelpw/zabbix-promise#3]
Hi Sumit, thanks for sharing your works.
i hope you'll give me some clarification on how to make use of zabbix api.

currently am having NodeJs app which consuming Twitter api to get streaming data. everything is running as headless. i just want to monitor my app like following scenarios.
1. whether my app is running or not.
2. what error actually happens 
3. does the error has raised from twitter api call or from my node app.

also am having external api that ll make post call to send data to some other asp.net webservice

i hope you ll understand what am actually trying to ask(may be am not clear, sry for that)
last one is, how to monitor my using zabbix api with Nodejs?

kindly provide some example snippets.  

many thanks

**Comment by sumitgoelpw** [comment]
Hi @ImSuriya 

There are multiple ways to solve the problems you described, and I don't think this library is the answer to all your questions.

1. I think the best way to monitor the application availability is by running Zabbix built-in web checks. If you have some complex requirements, then you may want to look into Selenium and PhantomJS for scripting the scenario and use zabbix_sender to send the data to Zabbix.

2. You can technically use Zabbix to store all error logs, but I won't recommend that as that would kill the performance depending on your log data. To identify what errors are occurring I suggest storing the log data in a file and use Zabbix built-in log check to alert for errors.

3. In my opinion, Zabbix is not like other Application Performance Monitoring solution where application performance metrics is predefined. With Zabbix, you need to know what to want to monitor and decide how to implement the check. You may want to look for community templates on https://share.zabbix.com/ for Node.js application monitoring.

Hope that helps.

**Comment by ImSuriya** [comment]
@sumitgoelpw thanks for you clear explanation.
